<a href="https://colab.research.google.com/github/Yujin726/0624/blob/main/07_02_Numpy_colab_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📘 w3schools NumPy 튜토리얼

##**1. NumPy 시작하기**

(1) NumPy 가져오기

NumPy가 설치되면 키워드를 추가하여 응용 프로그램에 가져옵니다.

In [1]:
import numpy

(2) NumPy를 np로

In [2]:
import numpy as np


(3) NumPy 버전 확인


In [3]:
import numpy as np
print(np.__version__)

2.0.2


##**2. NumPy배열 만들기**

(1) NumPy ndarray 객체 만들기

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


(2) 배열의 차원

1) 0차원 배열

In [5]:
import numpy as np

arr = np.array(42)

print(arr)

42


2) 1차원 배열

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


3) 2차원 배열

In [7]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


4) 3차원 배열

In [8]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


(3) 차원 수 확인

In [9]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


(4) 5차원 배열 및 배열 수 확인

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


##**3. NumPy 배열 인덱싱**

# (1) Access 배열 요소

-> 배열 요소에 액세스하는 것과 동일

--> NumPy 배열의 인덱스는 0으로 시작, 이는 첫 번째 요소가 인덱스는 0, 두 번째는 인덱스 1

1) 배열에서 요소 가져오기

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


2) 배열에서 요소 가져오기 및 추가

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


(2) 배열에 액세스하기

In [14]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6
